apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudforms-backup-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: "/exports/cloudforms-backup"
    server: "<your-nfs-host-here>"
  persistentVolumeReclaimPolicy: Retain
